# Generated by Django 5.2.8 on 2025-11-09 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoints',
            fields=[
                ('ip_address', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('mac_address', models.CharField(max_length=17)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficLog',
            fields=[
                ('pk', models.CompositePrimaryKey('ip_src', 'ip_dst', blank=True, editable=False, primary_key=True, serialize=False)),
                ('data_in', models.BigIntegerField(default=0)),
                ('data_out', models.BigIntegerField(default=0)),
                ('interval_start', models.DateTimeField(auto_now=True)),
                ('ip_dst', models.GenericIPAddressField()),
                ('ip_src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.endpoints')),
            ],
        ),
    ]
