# Generated by Django 5.2.8 on 2025-11-09 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficlog',
            name='interval_start',
        ),
    ]
