# Generated by Django 5.2.8 on 2025-11-10 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_alter_trafficlog_protocol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endpoints',
            options={'verbose_name_plural': 'Endpoints'},
        ),
    ]
