# Generated by Django 5.2.8 on 2025-11-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0005_alter_endpoints_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoints',
            name='ip_address',
            field=models.GenericIPAddressField(primary_key=True, serialize=False, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='endpoints',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Seen'),
        ),
        migrations.AlterField(
            model_name='endpoints',
            name='mac_address',
            field=models.CharField(max_length=17, verbose_name='MAC Address'),
        ),
    ]
