# Generated by Django 5.2.8 on 2025-11-30 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_alter_endpoints_ip_address_alter_endpoints_last_seen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirusTotalLog',
            fields=[
                ('ip_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='virustotal_log', serialize=False, to='dash.endpoints')),
                ('scanned_at', models.DateTimeField(auto_now=True)),
                ('malicious', models.IntegerField(default=0)),
                ('suspicious', models.IntegerField(default=0)),
                ('harmless', models.IntegerField(default=0)),
                ('undetected', models.IntegerField(default=0)),
                ('api_response', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
