# Generated by Django 5.2.8 on 2025-12-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0007_virustotallog'),
    ]

    operations = [
        migrations.AddField(
            model_name='virustotallog',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='virustotallog',
            name='owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
