# Generated by Django 5.2.8 on 2025-12-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0008_virustotallog_country_virustotallog_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoints',
            name='resolution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
