# Generated by Django 5.2.8 on 2025-12-07 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0009_endpoints_resolution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficlog',
            name='data_in',
        ),
    ]
