# Generated by Django 5.2.8 on 2025-12-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0010_remove_trafficlog_data_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficlog',
            name='data_in',
            field=models.BigIntegerField(default=0),
        ),
    ]
